import { useCallback, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { fetchPlayerDashboard } from '../../services/playerApi.js';
import { useSocket } from '../../context/SocketContext.jsx';

function Empty({ children, action, to }) { return <div className="dashboard-empty"><p>{children}</p>{action && <Link className="button secondary-button" to={to}>{action}</Link>}</div>; }
function ErrorState({ message, retry }) { return <div className="dashboard-error" role="alert"><span>{message}</span><button className="text-button" type="button" onClick={retry}>Retry</button></div>; }
function Skeleton({ wide = false }) { return <div className={wide ? 'dashboard-skeleton skeleton-wide' : 'dashboard-skeleton'} aria-hidden="true"><span /><span /><span /></div>; }
function Status({ value }) { return <span className={`dashboard-status status-${String(value || '').toLowerCase()}`}>{String(value || 'UNKNOWN').replaceAll('_', ' ')}</span>; }

function DashboardHeader({ dashboard }) { const user = dashboard.user; const active = dashboard.activeTournaments.filter((item) => item.status === 'LIVE').length; const subtitle = dashboard.upcomingMatches.length ? 'Your next match is coming up soon.' : active ? 'You have active tournament activity waiting for you.' : 'You are all caught up.'; return <div className="dashboard-welcome"><div><div className="page-kicker">Player command center</div><h1>Welcome back, {user.name}</h1><p>{subtitle}</p></div><div className="dashboard-identity"><span className="player-avatar">{user.name.slice(0, 1).toUpperCase()}</span><div><strong>{user.name}</strong><span>PLAYER · {user.profile?.uniquePlayerId || 'Verified account'}</span></div></div></div>; }

function Summary({ summary }) { const items = [['TEAMS', summary.teams], ['ACTIVE TOURNAMENTS', summary.activeTournaments], ['UPCOMING MATCHES', summary.upcomingMatches], ['COMPLETED', summary.completedTournaments]]; return <div className="dashboard-summary">{items.map(([label, value]) => <div className="summary-tile" key={label}><span>{label}</span><strong>{value}</strong><i /></div>)}</div>; }

function ActiveTournaments({ tournaments }) { const active = tournaments.filter((item) => item.status !== 'COMPLETED'); return <section className="dashboard-section active-tournaments"><div className="dashboard-section-head"><div><span className="section-label">Competition</span><h2>My tournaments</h2></div><Link className="text-link" to="/tournaments">Browse tournaments</Link></div>{!active.length ? <Empty action="Browse tournaments" to="/tournaments">You are not participating in any tournaments yet.</Empty> : <div className="dashboard-tournament-list">{active.map((item) => <article className="dashboard-tournament" key={item.id}><div className="tournament-accent" /><div className="dashboard-tournament-top"><Status value={item.status} /><span>{item.registrationStatus}</span></div><h3>{item.name}</h3><p>{item.teamName || 'Team registration'}{item.currentRound ? ` · ${item.currentRound}` : ''}{item.currentGroup ? ` · ${item.currentGroup}` : ''}</p><Link className="text-arrow" to={`/player/communications/${item.id}`}>Open tournament <span>↗</span></Link></article>)}</div>}</section>; }

function NextMatch({ matches }) { const match = matches[0]; return <section className="dashboard-section next-match"><div className="dashboard-section-head"><div><span className="section-label">Next action</span><h2>Upcoming match</h2></div></div>            { !match ? <Empty action="View my tournaments" to="/player/my-tournaments">No upcoming matches.</Empty> : <div className="next-match-card"><div><Status value={match.status} /><h3>{match.tournamentName}</h3><p>{match.roundName} · {match.groupName} · Match {match.matchNumber}</p><strong>{match.teamName}</strong></div><div className="match-time"><span>Scheduled</span><strong>{new Date(match.scheduledAt).toLocaleString()}</strong><Link className="button primary-button" to={`/player/communications/${match.tournamentId}`}>Open tournament</Link></div></div>}</section>; }

function Teams({ teams }) { return <section className="dashboard-section"><div className="dashboard-section-head"><div><span className="section-label">Roster</span><h2>My teams</h2></div><Link className="text-link" to="/player/teams">Manage teams</Link></div>{!teams.length ? <Empty action="Create team" to="/player/teams">You haven’t created or joined a team yet.</Empty> : <div className="dashboard-team-list">{teams.slice(0, 4).map((team) => <Link className="dashboard-team" to={`/player/teams`} key={team.id}><span className="team-badge">{team.name.slice(0, 1).toUpperCase()}</span><span><strong>{team.name}</strong><small>{team.member_count} members · Owner: {team.owner_name}</small></span><span>→</span></Link>)}</div>}</section>; }

function Results({ results }) { return <section className="dashboard-section"><div className="dashboard-section-head"><div><span className="section-label">Competition history</span><h2>Recent results</h2></div></div>{!results.length ? <Empty action="Open history" to="/history">No match results available yet.</Empty> : <div className="dashboard-result-list">{results.map((item) => <Link className="dashboard-result" to={`/player/communications/${item.tournamentId}?tab=group&subtab=matches`} key={item.id}><div><strong>{item.teamName}</strong><span>{item.tournamentName} · {item.roundName} · {item.groupName}</span></div><div><b>{item.points} pts</b><span>{item.kills} kills{item.placement ? ` · rank ${item.placement}` : ''}</span></div></Link>)}</div>}</section>; }

function Leaderboard({ items }) { const item = items[0]; return <section className="dashboard-section"><div className="dashboard-section-head"><div><span className="section-label">Standings</span><h2>Leaderboard snapshot</h2></div></div>{!item ? <Empty action="Explore tournaments" to="/tournaments">No leaderboard data available yet.</Empty> : <Link className="leaderboard-snapshot" to={`/player/communications/${item.tournamentId}?tab=leaderboard`}><div><span>{item.tournamentName}</span><strong>{item.teamName}</strong><small>{item.roundName} · {item.groupName}</small></div><div className="leaderboard-score"><b>{item.points}</b><span>points</span><b>{item.kills}</b><span>kills</span></div></Link>}</section>; }

function Announcements({ items }) { return <section className="dashboard-section"><div className="dashboard-section-head"><div><span className="section-label">Keep informed</span><h2>Recent announcements</h2></div></div>{!items.length ? <Empty action="Browse tournaments" to="/tournaments">No announcements from your tournaments.</Empty> : <div className="dashboard-announcements">{items.slice(0, 4).map((item) => <Link className="dashboard-announcement" to={`/player/communications/${item.tournamentId}?tab=overview`} key={item.id}><div><strong>{item.tournamentName}</strong><p>{item.message}</p><small>{item.creatorName} · {new Date(item.createdAt).toLocaleString()}</small></div></Link>)}</div>}</section>; }

function Activity({ items }) { return <section className="dashboard-section"><div className="dashboard-section-head"><div><span className="section-label">Timeline</span><h2>Recent activity</h2></div><Link className="text-link" to="/notifications">View notifications</Link></div>{!items.length ? <Empty>No recent activity.</Empty> : <div className="activity-list">{items.map((item) => <Link className="activity-item" to={item.tournamentId ? `/player/communications/${item.tournamentId}` : '/notifications'} key={item.id}><span className="activity-dot" /><div><strong>{item.type.replaceAll('_', ' ')}</strong><p>{item.content}</p></div><time>{new Date(item.createdAt).toLocaleDateString()}</time></Link>)}</div>}</section>; }

export function PlayerDashboardPage() { const { joinTournament, on } = useSocket(); const [dashboard, setDashboard] = useState(null); const [state, setState] = useState({ loading: true, error: '' }); const load = useCallback(async () => { setState({ loading: true, error: '' }); try { const data = await fetchPlayerDashboard(); setDashboard(data); data.activeTournaments.forEach((item) => joinTournament(item.id)); setState({ loading: false, error: '' }); } catch (error) { setState({ loading: false, error: error.message || 'Unable to load your dashboard.' }); } }, [joinTournament]); useEffect(() => { load(); }, [load]); useEffect(() => { const refresh = () => load(); const removeAnnouncement = on('announcement', refresh); const removeNotification = on('notification', refresh); const removeResult = on('result_upload', refresh); const removeLeaderboard = on('leaderboard_update', refresh); return () => { removeAnnouncement(); removeNotification(); removeResult(); removeLeaderboard(); }; }, [load, on]); if (state.loading) return <section className="dashboard-page"><Skeleton wide /><Skeleton /><Skeleton wide /></section>; if (!dashboard) return <section className="dashboard-page"><ErrorState message={state.error} retry={load} /></section>; return <section className="dashboard-page"><DashboardHeader dashboard={dashboard} /><Summary summary={dashboard.summary} /><div className="dashboard-priority"><NextMatch matches={dashboard.upcomingMatches} /><ActiveTournaments tournaments={dashboard.activeTournaments} /></div><div className="dashboard-columns"><div><Teams teams={dashboard.teams} /><Results results={dashboard.recentResults} /><Announcements items={dashboard.recentAnnouncements} /></div><div><Leaderboard items={dashboard.leaderboardSnapshots} /><Activity items={dashboard.actionRequired} /><section className="dashboard-section quick-actions"><div className="dashboard-section-head"><div><span className="section-label">Shortcuts</span><h2>Quick actions</h2></div></div><div className="quick-action-grid"><Link to="/player/teams">Create or manage teams</Link><Link to="/tournaments">Browse tournaments</Link><Link to="/history">View history</Link><Link to="/notifications">Open notifications</Link></div></section></div></div></section>; }
