import { useCallback, useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { fetchRegistrations, fetchTournament, reviewRegistration, updateTournament } from '../../services/tournamentApi.js';

export function OrganizerTournamentPage() {
  const { tournamentId } = useParams();
  const [tournament, setTournament] = useState(null);
  const [registrations, setRegistrations] = useState([]);
  const [state, setState] = useState({ loading: true, error: '', notice: '' });
  const load = useCallback(async () => { try { const [tournamentResult, registrationsResult] = await Promise.all([fetchTournament(tournamentId), fetchRegistrations(tournamentId)]); setTournament(tournamentResult.tournament); setRegistrations(registrationsResult.registrations); setState({ loading: false, error: '', notice: '' }); } catch (error) { setState({ loading: false, error: error.message, notice: '' }); } }, [tournamentId]);
  useEffect(() => { load(); }, [load]);
  async function transition(status) { try { const result = await updateTournament(tournamentId, { status }); setTournament(result.tournament); setState((current) => ({ ...current, notice: `Tournament moved to ${status}.`, error: '' })); } catch (error) { setState((current) => ({ ...current, error: error.message, notice: '' })); } }
  async function review(registrationId, status) { try { await reviewRegistration(registrationId, { status, rejectionReason: status === 'REJECTED' ? 'Registration did not pass organizer review.' : undefined }); await load(); } catch (error) { setState((current) => ({ ...current, error: error.message })); } }
  if (state.loading) return <section className="workspace-page"><p className="status-panel">Loading tournament...</p></section>;
  if (!tournament) return <section className="workspace-page"><div className="form-alert" role="alert">{state.error}</div></section>;
  return <section className="workspace-page"><Link className="text-link" to="/organizer/tournaments">Back to tournaments</Link><div className="page-kicker">{tournament.status.replaceAll('_', ' ')}</div><h1>{tournament.name}</h1><p>{tournament.description || 'No description provided.'}</p>{state.error && <div className="form-alert" role="alert">{state.error}</div>}{state.notice && <div className="success-alert" role="status">{state.notice}</div>}<div className="detail-grid"><div className="detail-panel"><strong>Teams</strong><span>{tournament.maxTeams}</span></div><div className="detail-panel"><strong>Players/team</strong><span>{tournament.playersPerTeam}</span></div><div className="detail-panel"><strong>Entry</strong><span>{tournament.entryType === 'PAID' ? tournament.entryFee : 'Free'}</span></div></div><div className="lifecycle-actions">{tournament.status === 'DRAFT' && <button className="button primary-button" onClick={() => transition('REGISTRATION_OPEN')}>Open registration</button>}{tournament.status === 'REGISTRATION_OPEN' && <button className="button secondary-button" onClick={() => transition('REGISTRATION_CLOSED')}>Close registration</button>}{tournament.status === 'REGISTRATION_CLOSED' && <button className="button primary-button" onClick={() => transition('LIVE')}>Start tournament</button>}</div><div className="registration-list"><div className="section-heading"><h2>Registrations</h2><span>{registrations.length}</span></div>{registrations.length === 0 && <p className="empty-state">No registrations found.</p>}{registrations.map((registration) => <article className="registration-item" key={registration.id}><div><strong>{registration.teamName}</strong><p>{registration.members.map((member) => `${member.name} (${member.uniquePlayerId})`).join(', ')}</p>{registration.transactionId && <p>Transaction: {registration.transactionId}</p>}</div><div className="registration-actions"><span className={`status-badge ${registration.status.toLowerCase()}`}>{registration.status}</span>{registration.status === 'PENDING' && <><button className="text-button" onClick={() => review(registration.id, 'VERIFIED')}>Verify</button><button className="text-button danger-text" onClick={() => review(registration.id, 'REJECTED')}>Reject</button></>}</div></article>)}</div></section>;
}
