import { useCallback, useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { createRound, fetchRounds, updateRound } from '../../services/competitionApi.js';

export function OrganizerRoundsPage() {
  const { tournamentId } = useParams(); const [rounds, setRounds] = useState([]); const [form, setForm] = useState({ roundNumber: 1, name: 'Round 1' }); const [state, setState] = useState({ loading: true, error: '', notice: '' });
  const load = useCallback(async () => { try { const result = await fetchRounds(tournamentId); setRounds(result.rounds); setState((s) => ({ ...s, loading: false })); } catch (error) { setState({ loading: false, error: error.message, notice: '' }); } }, [tournamentId]);
  useEffect(() => { load(); }, [load]);
  async function submit(event) { event.preventDefault(); try { const result = await createRound(tournamentId, { roundNumber: Number(form.roundNumber), name: form.name }); setRounds((current) => [...current, result.round].sort((a, b) => a.roundNumber - b.roundNumber)); setState((s) => ({ ...s, error: '', notice: 'Round created.' })); } catch (error) { setState((s) => ({ ...s, error: error.message, notice: '' })); } }
  async function start(round) { try { const result = await updateRound(round.id, { status: 'IN_PROGRESS' }); setRounds((current) => current.map((item) => item.id === round.id ? result.round : item)); } catch (error) { setState((s) => ({ ...s, error: error.message })); } }
  return <section className="workspace-page"><Link className="text-link" to={`/organizer/tournaments/${tournamentId}`}>Back to tournament</Link><div className="page-kicker">Competition setup</div><h1>Rounds</h1><p>Build the tournament progression and open each round for group operations.</p>{state.error && <div className="form-alert" role="alert">{state.error}</div>}{state.notice && <div className="success-alert" role="status">{state.notice}</div>}<div className="organizer-grid"><form className="team-form" onSubmit={submit}><h2>Create round</h2><label htmlFor="round-number">Round number</label><input id="round-number" type="number" min="1" value={form.roundNumber} onChange={(e) => setForm({ roundNumber: e.target.value, name: `Round ${e.target.value}` })} /><label htmlFor="round-name">Name</label><input id="round-name" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} required /><button className="button primary-button" type="submit">Create round</button></form><div className="team-list"><h2>Rounds</h2>{state.loading && <p className="status-panel">Loading rounds...</p>}{!state.loading && !rounds.length && <p className="empty-state">No rounds created yet.</p>}{rounds.map((round) => <div className="competition-item" key={round.id}><div><span className="tournament-status">Round {round.roundNumber} · {round.status.replaceAll('_', ' ')}</span><h3>{round.name}</h3></div><div className="competition-actions">{round.status === 'NOT_STARTED' && <button className="button secondary-button" type="button" onClick={() => start(round)}>Start</button>}<Link className="button ghost-button" to={`/organizer/tournaments/${tournamentId}/rounds/${round.id}/groups`}>Groups</Link></div></div>)}</div></div></section>;
}
