import { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { completeTournament } from '../../services/archiveApi.js';

export function OrganizerCompletionPage() {
  const { tournamentId } = useParams(); const [archive, setArchive] = useState(null); const [state, setState] = useState({ submitting: false, error: '', notice: '' });
  async function submit() { setState({ submitting: true, error: '', notice: '' }); try { const result = await completeTournament(tournamentId); setArchive(result.archive); setState({ submitting: false, error: '', notice: 'Tournament completed and archived.' }); } catch (error) { setState({ submitting: false, error: error.message, notice: '' }); } }
  return <section className="workspace-page"><Link className="text-link" to={`/organizer/tournaments/${tournamentId}`}>Back to tournament</Link><div className="page-kicker">Finalization</div><h1>Complete tournament</h1><p>Completion locks live operations and preserves a lightweight history snapshot.</p>{state.error && <div className="form-alert" role="alert">{state.error}</div>}{state.notice && <div className="success-alert" role="status">{state.notice}</div>}{!archive && <div className="team-form"><h2>Final checks</h2><p>All final-round groups, matches, qualifications, and leaderboard entries must be complete.</p><button className="button primary-button" type="button" onClick={submit} disabled={state.submitting}>{state.submitting ? 'Finalizing...' : 'Complete and archive'}</button></div>}{archive && <div className="team-list"><h2>{archive.tournamentName}</h2><p>Completed {new Date(archive.completedAt).toLocaleString()} · {archive.registrationCount} registrations</p><h3>Winners</h3>{archive.winners.map((winner) => <div className="competition-item" key={winner.teamId}><strong>#{winner.rank} {winner.teamName}</strong><span>{winner.points} points</span></div>)}<Link className="button secondary-button" to={`/history/${archive.id}`}>Open archive</Link></div>}</section>;
}
