import { useCallback, useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { assignTeam, createGroup, fetchEligibleTeams, fetchGroups } from '../../services/competitionApi.js';

export function OrganizerGroupsPage() {
  const { tournamentId, roundId } = useParams(); const [groups, setGroups] = useState([]); const [teams, setTeams] = useState([]); const [form, setForm] = useState({ name: '', groupSize: 4 }); const [state, setState] = useState({ loading: true, error: '', notice: '' });
  const load = useCallback(async () => { try { const [groupResult, teamResult] = await Promise.all([fetchGroups(roundId), fetchEligibleTeams(roundId)]); setGroups(groupResult.groups); setTeams(teamResult.teams); setState((s) => ({ ...s, loading: false })); } catch (error) { setState({ loading: false, error: error.message, notice: '' }); } }, [roundId]); useEffect(() => { load(); }, [load]);
  async function submit(event) { event.preventDefault(); try { const result = await createGroup(roundId, { ...form, groupSize: Number(form.groupSize) }); setGroups((current) => [...current, result.group]); setForm({ name: '', groupSize: 4 }); setState((s) => ({ ...s, error: '', notice: 'Group created.' })); } catch (error) { setState((s) => ({ ...s, error: error.message, notice: '' })); } }
  async function assign(groupId, teamId) { if (!teamId) return; try { const result = await assignTeam(groupId, teamId); setGroups((current) => current.map((group) => group.id === groupId ? result.group : group)); setState((s) => ({ ...s, error: '', notice: 'Eligible team assigned.' })); } catch (error) { setState((s) => ({ ...s, error: error.message, notice: '' })); } }
  const assigned = new Set(groups.flatMap((group) => (group.teams || []).map((team) => String(team.id))));
  return <section className="workspace-page"><Link className="text-link" to={`/organizer/tournaments/${tournamentId}/rounds`}>Back to rounds</Link><div className="page-kicker">Round {roundId}</div><h1>Groups</h1><p>Assign eligible verified or qualified teams to groups and prepare match rooms.</p>{state.error && <div className="form-alert" role="alert">{state.error}</div>}{state.notice && <div className="success-alert" role="status">{state.notice}</div>}<div className="organizer-grid"><form className="team-form" onSubmit={submit}><h2>Create group</h2><label htmlFor="group-name">Name</label><input id="group-name" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} required /><label htmlFor="group-size">Group size</label><input id="group-size" type="number" min="1" value={form.groupSize} onChange={(e) => setForm({ ...form, groupSize: e.target.value })} /><button className="button primary-button" type="submit">Create group</button></form><div className="team-list"><h2>Groups</h2>{state.loading && <p className="status-panel">Loading groups...</p>}{!state.loading && !groups.length && <p className="empty-state">No groups created yet.</p>}{groups.map((group) => <div className="competition-item" key={group.id}><div><span className="tournament-status">{group.status.replaceAll('_', ' ')}</span><h3>{group.name}</h3><p>{group.teams?.length || 0} / {group.groupSize} teams assigned</p></div><div className="competition-actions"><select aria-label={`Assign team to ${group.name}`} defaultValue="" onChange={(e) => assign(group.id, e.target.value)} disabled={group.status === 'COMPLETED'}><option value="">Assign eligible team</option>{teams.filter((team) => !assigned.has(String(team.id))).map((team) => <option key={team.id} value={team.id}>{team.name}</option>)}</select><Link className="button ghost-button" to={`/organizer/tournaments/${tournamentId}/groups/${group.id}`}>Open group</Link></div></div>)}</div></div></section>;
}
