import { useCallback, useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { fetchQualifications, fetchRoundLeaderboard, removeQualification, selectQualification } from '../../services/competitionApi.js';

export function OrganizerQualificationsPage() {
  const { tournamentId, roundId } = useParams(); const [leaderboard, setLeaderboard] = useState([]); const [qualifications, setQualifications] = useState([]); const [state, setState] = useState({ loading: true, error: '', notice: '' });
  const load = useCallback(async () => { try { const [leaderboardResult, qualificationResult] = await Promise.all([fetchRoundLeaderboard(roundId), fetchQualifications(roundId)]); setLeaderboard(leaderboardResult.leaderboard); setQualifications(qualificationResult.qualifications); setState((s) => ({ ...s, loading: false })); } catch (error) { setState({ loading: false, error: error.message, notice: '' }); } }, [roundId]); useEffect(() => { load(); }, [load]);
  async function toggle(teamId) { try { const exists = qualifications.some((item) => String(item.teamId) === String(teamId)); const result = exists ? await removeQualification(roundId, teamId) : await selectQualification(roundId, teamId); setQualifications(result.qualifications); setState((s) => ({ ...s, error: '', notice: exists ? 'Qualification removed.' : 'Team qualified for the next round.' })); } catch (error) { setState((s) => ({ ...s, error: error.message, notice: '' })); } }
  return <section className="workspace-page"><Link className="text-link" to={`/organizer/tournaments/${tournamentId}/rounds`}>Back to rounds</Link><div className="page-kicker">Qualification</div><h1>Select qualifiers</h1><p>Qualification is an explicit organizer decision based on the persisted round standings.</p>{state.error && <div className="form-alert" role="alert">{state.error}</div>}{state.notice && <div className="success-alert" role="status">{state.notice}</div>}<div className="team-list">{state.loading && <p className="status-panel">Loading standings...</p>}{!state.loading && !leaderboard.length && <p className="empty-state">No finalized standings are available yet.</p>}{leaderboard.map((entry) => { const selected = qualifications.some((item) => String(item.teamId) === String(entry.teamId)); return <div className="competition-item" key={entry.teamId}><div><span className="tournament-status">Round points: {entry.points}</span><h3>{entry.teamName}</h3><p>{entry.kills} kills · {entry.matchesPlayed} matches</p></div><button className={selected ? 'button primary-button' : 'button secondary-button'} type="button" onClick={() => toggle(entry.teamId)}>{selected ? 'Qualified' : 'Select qualifier'}</button></div>; })}</div></section>;
}
