import { useCallback, useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { completeMatch, createMatch, fetchGroup, updateGroup, updateMatch } from '../../services/competitionApi.js';

export function OrganizerGroupPage() {
  const { tournamentId, groupId } = useParams(); const [group, setGroup] = useState(null); const [form, setForm] = useState({ matchNumber: 1, name: 'Match 1' }); const [room, setRoom] = useState({ roomId: '', roomPassword: '' }); const [state, setState] = useState({ loading: true, error: '', notice: '' });
  const load = useCallback(async () => { try { const result = await fetchGroup(groupId); setGroup(result.group); setRoom({ roomId: result.group.roomId || '', roomPassword: result.group.roomPassword || '' }); setState((s) => ({ ...s, loading: false })); } catch (error) { setState({ loading: false, error: error.message, notice: '' }); } }, [groupId]); useEffect(() => { load(); }, [load]);
  async function saveRoom(event) { event.preventDefault(); try { const result = await updateGroup(groupId, room); setGroup(result.group); setState((s) => ({ ...s, error: '', notice: 'Room details saved.' })); } catch (error) { setState((s) => ({ ...s, error: error.message })); } }
  async function startGroup() { try { const result = await updateGroup(groupId, { status: 'IN_PROGRESS' }); setGroup(result.group); } catch (error) { setState((s) => ({ ...s, error: error.message })); } }
  async function addMatch(event) { event.preventDefault(); try { const result = await createMatch(groupId, { ...form, matchNumber: Number(form.matchNumber) }); setGroup((current) => ({ ...current, matches: [...(current.matches || []), result.match] })); setForm({ matchNumber: Number(form.matchNumber) + 1, name: `Match ${Number(form.matchNumber) + 1}` }); } catch (error) { setState((s) => ({ ...s, error: error.message })); } }
  async function setMatchStatus(match, status) { try { const result = status === 'COMPLETED' ? await completeMatch(match.id) : await updateMatch(match.id, { status }); setGroup((current) => ({ ...current, matches: current.matches.map((item) => item.id === match.id ? result.match : item) })); } catch (error) { setState((s) => ({ ...s, error: error.message })); } }
  if (state.loading) return <section className="workspace-page"><p className="status-panel">Loading group...</p></section>; if (!group) return <section className="workspace-page"><div className="form-alert" role="alert">{state.error}</div></section>;
  return <section className="workspace-page"><Link className="text-link" to={`/organizer/tournaments/${tournamentId}/rounds`}>Back to rounds</Link><div className="page-kicker">Group operations</div><h1>{group.name}</h1><p>{group.teams?.length || 0} assigned teams · {group.status.replaceAll('_', ' ')}</p>{state.error && <div className="form-alert" role="alert">{state.error}</div>}{state.notice && <div className="success-alert" role="status">{state.notice}</div>}<div className="competition-layout"><form className="team-form" onSubmit={saveRoom}><h2>Room details</h2><label htmlFor="room-id">Room ID</label><input id="room-id" value={room.roomId} onChange={(e) => setRoom({ ...room, roomId: e.target.value })} /><label htmlFor="room-password">Room password</label><input id="room-password" value={room.roomPassword} onChange={(e) => setRoom({ ...room, roomPassword: e.target.value })} /><button className="button primary-button" type="submit">Save room</button>{group.status === 'NOT_STARTED' && <button className="button secondary-button" type="button" onClick={startGroup}>Start group</button>}</form><div className="team-list"><div className="section-heading"><h2>Matches</h2><form className="inline-form" onSubmit={addMatch}><input aria-label="Match number" type="number" min="1" value={form.matchNumber} onChange={(e) => setForm({ ...form, matchNumber: e.target.value })} /><input aria-label="Match name" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /><button className="button primary-button" type="submit" disabled={group.status === 'COMPLETED'}>Add match</button></form></div>{!group.matches?.length && <p className="empty-state">No matches created yet.</p>}{group.matches?.map((match) => <div className="competition-item" key={match.id}><div><span className="tournament-status">Match {match.matchNumber} · {match.status}</span><h3>{match.name}</h3></div><div className="competition-actions">{match.status === 'SCHEDULED' && <button className="button secondary-button" type="button" onClick={() => setMatchStatus(match, 'LIVE')}>Start</button>}{match.status === 'LIVE' && <button className="button secondary-button" type="button" onClick={() => setMatchStatus(match, 'COMPLETED')}>Complete</button>}</div></div>)}</div></div></section>;
}
