import { asyncHandler } from '../utils/asyncHandler.js';
import * as service from '../services/competitionService.js';
import { emitRealtime } from '../utils/realtimeHub.js';

export const listRounds = asyncHandler(async (req, res) => res.json({ rounds: await service.listTournamentRounds(Number(req.params.tournamentId), req.user.id) }));
export const getRound = asyncHandler(async (req, res) => res.json({ round: await service.getRound(Number(req.params.roundId), req.user.id) }));
export const createRound = asyncHandler(async (req, res) => res.status(201).json({ round: await service.createTournamentRound(Number(req.params.tournamentId), req.body, req.user.id) }));
export const updateRoundStatus = asyncHandler(async (req, res) => { const round = await service.updateRoundStatus(Number(req.params.roundId), req.body.status, req.user.id); emitRealtime(`round_${round.id}`, 'round_status', round); res.json({ round }); });
export const completeRound = asyncHandler(async (req, res) => res.json({ round: await service.completeRound(Number(req.params.roundId), req.user.id) }));
export const listGroups = asyncHandler(async (req, res) => res.json({ groups: await service.listRoundGroups(Number(req.params.roundId), req.user.id) }));
export const listPlayerTournamentGroups = asyncHandler(async (req, res) => res.json({ groups: await service.listPlayerTournamentGroups(Number(req.params.tournamentId), req.user.id) }));
export const listEligibleTeams = asyncHandler(async (req, res) => res.json({ teams: await service.listEligibleRoundTeams(Number(req.params.roundId), req.user.id) }));
export const getGroup = asyncHandler(async (req, res) => res.json({ group: await service.getGroup(Number(req.params.groupId), req.user.id) }));
export const createGroup = asyncHandler(async (req, res) => res.status(201).json({ group: await service.createRoundGroup(Number(req.params.roundId), req.body, req.user.id) }));
export const updateGroup = asyncHandler(async (req, res) => { const group = await service.updateRoundGroup(Number(req.params.groupId), req.body, req.user.id); emitRealtime(`group_${group.id}`, 'room_update', group); if (req.body.status) emitRealtime(`group_${group.id}`, 'group_status', group); res.json({ group }); });
export const completeGroup = asyncHandler(async (req, res) => { const group = await service.updateRoundGroup(Number(req.params.groupId), { status: 'COMPLETED' }, req.user.id); emitRealtime(`group_${group.id}`, 'group_status', group); res.json({ group }); });
export const assignTeam = asyncHandler(async (req, res) => res.status(201).json({ group: await service.assignVerifiedTeam(Number(req.params.groupId), Number(req.params.teamId), req.user.id) }));
export const removeTeam = asyncHandler(async (req, res) => res.json({ group: await service.removeAssignedTeam(Number(req.params.groupId), Number(req.params.teamId), req.user.id) }));
export const listMatches = asyncHandler(async (req, res) => res.json({ matches: await service.listGroupMatches(Number(req.params.groupId), req.user.id) }));
export const getMatch = asyncHandler(async (req, res) => res.json({ match: await service.getMatch(Number(req.params.matchId), req.user.id) }));
export const createMatch = asyncHandler(async (req, res) => res.status(201).json({ match: await service.createGroupMatch(Number(req.params.groupId), req.body, req.user.id) }));
export const updateMatch = asyncHandler(async (req, res) => res.json({ match: await service.updateGroupMatch(Number(req.params.matchId), req.body, req.user.id) }));
export const completeMatch = asyncHandler(async (req, res) => res.json({ match: await service.completeMatch(Number(req.params.matchId), req.user.id) }));
export const autoAssign = asyncHandler(async (req, res) => res.json(await service.autoAssignRoundGroups(Number(req.params.roundId), req.body, req.user.id)));
export const bulkMove = asyncHandler(async (req, res) => res.json(await service.bulkMoveRoundTeams(Number(req.params.roundId), req.body, req.user.id)));
export const lockAssignment = asyncHandler(async (req, res) => res.json({ round: await service.lockRoundAssignment(Number(req.params.roundId), req.user.id) }));
export const createNextRound = asyncHandler(async (req, res) => res.status(201).json(await service.createNextTournamentRound(Number(req.params.tournamentId), req.body, req.user.id)));
