import { pool } from '../config/database.js';

const roundFields = 'id, tournament_id, round_number, name, status, started_at, completed_at, created_at, updated_at';
const groupFields = 'id, round_id, name, status, group_size, room_id, room_password, started_at, completed_at, created_at, updated_at';
const matchFields = 'id, group_id, match_number, name, status, scheduled_at, started_at, completed_at, created_at, updated_at';

export async function getTournamentContext(tournamentId) { const [rows] = await pool.query('SELECT id, organizer_id, status FROM tournaments WHERE id = ?', [tournamentId]); return rows[0] || null; }
export async function getRoundContext(roundId) { const [rows] = await pool.query(`SELECT r.*, t.organizer_id, t.status AS tournament_status FROM rounds r JOIN tournaments t ON t.id = r.tournament_id WHERE r.id = ?`, [roundId]); return rows[0] || null; }
export async function getGroupContext(groupId) { const [rows] = await pool.query(`SELECT g.*, r.tournament_id, r.status AS round_status, t.organizer_id, t.status AS tournament_status FROM \`groups\` g JOIN rounds r ON r.id = g.round_id JOIN tournaments t ON t.id = r.tournament_id WHERE g.id = ?`, [groupId]); return rows[0] || null; }
export async function isPlayerAssignedToGroup(groupId, userId) { const [rows] = await pool.query('SELECT 1 FROM group_teams gt JOIN team_members tm ON tm.team_id = gt.team_id WHERE gt.group_id = ? AND tm.user_id = ? LIMIT 1', [groupId, userId]); return Boolean(rows[0]); }
export async function getMatchContext(matchId) { const [rows] = await pool.query(`SELECT m.*, g.round_id, r.tournament_id, g.status AS group_status, r.status AS round_status, t.organizer_id, t.status AS tournament_status FROM matches m JOIN \`groups\` g ON g.id = m.group_id JOIN rounds r ON r.id = g.round_id JOIN tournaments t ON t.id = r.tournament_id WHERE m.id = ?`, [matchId]); return rows[0] || null; }

export async function listRounds(tournamentId) { const [rows] = await pool.query(`SELECT ${roundFields} FROM rounds WHERE tournament_id = ? ORDER BY round_number`, [tournamentId]); return rows; }
export async function findRound(roundId) { const [rows] = await pool.query(`SELECT ${roundFields} FROM rounds WHERE id = ?`, [roundId]); return rows[0] || null; }
export async function createRound(tournamentId, input) { const [result] = await pool.query('INSERT INTO rounds (tournament_id, round_number, name) VALUES (?, ?, ?)', [tournamentId, input.roundNumber, input.name.trim()]); return findRound(result.insertId); }
export async function updateRound(roundId, status) { await pool.query('UPDATE rounds SET status = ?, started_at = CASE WHEN ? = \'IN_PROGRESS\' AND started_at IS NULL THEN CURRENT_TIMESTAMP ELSE started_at END, completed_at = CASE WHEN ? = \'COMPLETED\' THEN CURRENT_TIMESTAMP ELSE completed_at END WHERE id = ?', [status, status, status, roundId]); return findRound(roundId); }
export async function countIncompleteGroups(roundId) { const [rows] = await pool.query("SELECT COUNT(*) AS count FROM `groups` WHERE round_id = ? AND status <> 'COMPLETED'", [roundId]); return Number(rows[0].count); }
export async function listEligibleTeams(roundId) { const [rounds] = await pool.query('SELECT id, tournament_id, round_number FROM rounds WHERE id = ?', [roundId]); if (!rounds[0]) return []; const round = rounds[0]; const [rows] = await pool.query(`SELECT DISTINCT teams.id, teams.name FROM teams JOIN registrations r ON r.team_id = teams.id AND r.tournament_id = ? AND r.status = 'VERIFIED' WHERE ${Number(round.round_number) === 1 ? '1 = 1' : 'EXISTS (SELECT 1 FROM qualifications q JOIN rounds previous_round ON previous_round.id = q.round_id WHERE previous_round.tournament_id = ? AND previous_round.round_number = ? AND q.team_id = teams.id)'} ORDER BY teams.name`, Number(round.round_number) === 1 ? [round.tournament_id] : [round.tournament_id, round.tournament_id, Number(round.round_number) - 1]); return rows; }

export async function listGroups(roundId) { const [rows] = await pool.query(`SELECT ${groupFields} FROM \`groups\` WHERE round_id = ? ORDER BY id`, [roundId]); return Promise.all(rows.map(async (group) => ({ ...group, teams: await listGroupTeams(group.id), matches: await listMatches(group.id) }))); }
export async function listPlayerTournamentGroups(tournamentId, userId) {
  const prefixedGroupFields = groupFields.split(', ').map((field) => `g.${field}`).join(', ');
  const [rows] = await pool.query(`SELECT DISTINCT ${prefixedGroupFields}, r.round_number FROM \`groups\` g JOIN rounds r ON r.id = g.round_id JOIN group_teams gt ON gt.group_id = g.id JOIN team_members tm ON tm.team_id = gt.team_id WHERE r.tournament_id = ? AND tm.user_id = ? ORDER BY r.round_number, g.id`, [tournamentId, userId]);
  return Promise.all(rows.map(async (group) => ({ ...group, teams: await listGroupTeams(group.id), matches: await listMatches(group.id) })));
}

export async function isPlayerAssignedToTournament(tournamentId, userId) {
  const [rows] = await pool.query('SELECT 1 FROM group_teams gt JOIN `groups` g ON g.id = gt.group_id JOIN rounds r ON r.id = g.round_id JOIN team_members tm ON tm.team_id = gt.team_id WHERE r.tournament_id = ? AND tm.user_id = ? LIMIT 1', [tournamentId, userId]);
  return Boolean(rows[0]);
}
export async function findGroup(groupId) { const [rows] = await pool.query(`SELECT ${groupFields} FROM \`groups\` WHERE id = ?`, [groupId]); if (!rows[0]) return null; return { ...rows[0], teams: await listGroupTeams(groupId), matches: await listMatches(groupId) }; }
export async function createGroup(roundId, input) { const [result] = await pool.query('INSERT INTO `groups` (round_id, name, group_size) VALUES (?, ?, ?)', [roundId, input.name.trim(), input.groupSize]); return findGroup(result.insertId); }
export async function updateGroup(groupId, input) { const allowed = { name: 'name', groupSize: 'group_size', roomId: 'room_id', roomPassword: 'room_password', status: 'status' }; const columns = []; const values = []; for (const [key, column] of Object.entries(allowed)) if (input[key] !== undefined) { columns.push(`${column} = ?`); values.push(input[key]); } if (columns.length) { values.push(groupId); await pool.query(`UPDATE \`groups\` SET ${columns.join(', ')}, started_at = CASE WHEN ? = 'IN_PROGRESS' AND started_at IS NULL THEN CURRENT_TIMESTAMP ELSE started_at END, completed_at = CASE WHEN ? = 'COMPLETED' THEN CURRENT_TIMESTAMP ELSE completed_at END WHERE id = ?`, [...values, input.status || '', input.status || '', groupId]); } return findGroup(groupId); }
export async function countIncompleteMatches(groupId) { const [rows] = await pool.query("SELECT COUNT(*) AS count FROM matches WHERE group_id = ? AND status <> 'COMPLETED'", [groupId]); return Number(rows[0].count); }
export async function listGroupTeams(groupId) { const [rows] = await pool.query('SELECT gt.team_id AS id, t.name, gt.assigned_at FROM group_teams gt JOIN teams t ON t.id = gt.team_id WHERE gt.group_id = ? ORDER BY t.name', [groupId]); return rows; }
export async function assignTeam(groupId, teamId) { const connection = await pool.getConnection(); try { await connection.beginTransaction(); const [groups] = await connection.query('SELECT g.id, g.round_id, g.status, g.group_size, r.tournament_id, r.round_number FROM `groups` g JOIN rounds r ON r.id = g.round_id WHERE g.id = ? FOR UPDATE', [groupId]); if (!groups[0]) return null; const [assigned] = await connection.query('SELECT COUNT(*) AS count FROM group_teams WHERE group_id = ?', [groupId]); if (Number(assigned[0].count) >= Number(groups[0].group_size)) { const error = new Error('This group has reached its maximum capacity'); error.code = 'GROUP_CAPACITY'; throw error; } const [registrations] = await connection.query("SELECT id FROM registrations WHERE tournament_id = ? AND team_id = ? AND status = 'VERIFIED' FOR UPDATE", [groups[0].tournament_id, teamId]); if (!registrations[0]) { const error = new Error('Only verified teams can be assigned'); error.code = 'TEAM_NOT_VERIFIED'; throw error; } let eligible = true; if (Number(groups[0].round_number) > 1) { const [qualifications] = await connection.query("SELECT q.id FROM qualifications q JOIN rounds previous_round ON previous_round.id = q.round_id WHERE previous_round.tournament_id = ? AND previous_round.round_number = ? AND q.team_id = ? LIMIT 1 FOR UPDATE", [groups[0].tournament_id, Number(groups[0].round_number) - 1, teamId]); eligible = Boolean(qualifications[0]); } if (!eligible) { const error = new Error('Team is not qualified for this round'); error.code = 'TEAM_NOT_QUALIFIED'; throw error; } const [existing] = await connection.query('SELECT gt.id FROM group_teams gt JOIN `groups` g ON g.id = gt.group_id WHERE g.round_id = ? AND gt.team_id = ? FOR UPDATE', [groups[0].round_id, teamId]); if (existing[0]) { const error = new Error('This team is already assigned to another group in this round'); error.code = 'TEAM_ALREADY_ASSIGNED'; throw error; } await connection.query('INSERT INTO group_teams (group_id, team_id) VALUES (?, ?)', [groupId, teamId]); await connection.commit(); return findGroup(groupId); } catch (error) { await connection.rollback(); throw error; } finally { connection.release(); } }
export async function removeTeam(groupId, teamId) { await pool.query('DELETE FROM group_teams WHERE group_id = ? AND team_id = ?', [groupId, teamId]); return findGroup(groupId); }

export async function listMatches(groupId) { const [rows] = await pool.query(`SELECT ${matchFields} FROM matches WHERE group_id = ? ORDER BY match_number`, [groupId]); return rows; }
export async function findMatch(matchId) { const [rows] = await pool.query(`SELECT ${matchFields} FROM matches WHERE id = ?`, [matchId]); return rows[0] || null; }
export async function createMatch(groupId, input) { const [result] = await pool.query('INSERT INTO matches (group_id, match_number, name, scheduled_at) VALUES (?, ?, ?, ?)', [groupId, input.matchNumber, input.name.trim(), input.scheduledAt || null]); return findMatch(result.insertId); }
export async function updateMatch(matchId, input) { const allowed = { name: 'name', status: 'status', scheduledAt: 'scheduled_at' }; const columns = []; const values = []; for (const [key, column] of Object.entries(allowed)) if (input[key] !== undefined) { columns.push(`${column} = ?`); values.push(key === 'name' ? input[key].trim() : input[key]); } if (columns.length) { values.push(matchId); await pool.query(`UPDATE matches SET ${columns.join(', ')}, started_at = CASE WHEN ? = 'LIVE' AND started_at IS NULL THEN CURRENT_TIMESTAMP ELSE started_at END, completed_at = CASE WHEN ? = 'COMPLETED' THEN CURRENT_TIMESTAMP ELSE completed_at END WHERE id = ?`, [...values, input.status || '', input.status || '', matchId]); } return findMatch(matchId); }
