import { pool } from '../config/database.js';

export async function getSummary(userId) {
  const [rows] = await pool.query(`SELECT
    (SELECT COUNT(DISTINCT tm.team_id) FROM team_members tm WHERE tm.user_id = ?) AS teams,
    (SELECT COUNT(DISTINCT r.tournament_id) FROM registrations r JOIN team_members tm ON tm.team_id = r.team_id WHERE tm.user_id = ? AND r.status IN ('PENDING','VERIFIED') AND r.tournament_id IN (SELECT id FROM tournaments WHERE status IN ('REGISTRATION_OPEN','REGISTRATION_CLOSED','LIVE'))) AS active_tournaments,
    (SELECT COUNT(DISTINCT m.id) FROM matches m JOIN \`groups\` g ON g.id = m.group_id JOIN rounds rd ON rd.id = g.round_id JOIN team_members tm ON tm.team_id IN (SELECT gt.team_id FROM group_teams gt WHERE gt.group_id = g.id) JOIN registrations r ON r.team_id = tm.team_id AND r.tournament_id = rd.tournament_id AND r.status = 'VERIFIED' WHERE tm.user_id = ? AND m.status <> 'COMPLETED' AND m.scheduled_at IS NOT NULL) AS upcoming_matches,
    (SELECT COUNT(DISTINCT r.tournament_id) FROM registrations r JOIN team_members tm ON tm.team_id = r.team_id JOIN tournaments t ON t.id = r.tournament_id WHERE tm.user_id = ? AND r.status = 'VERIFIED' AND t.status = 'COMPLETED') AS completed_tournaments`, [userId, userId, userId, userId]);
  return rows[0];
}

export async function listTeams(userId) { const [rows] = await pool.query(`SELECT t.id, t.name, t.owner_id, owner.name AS owner_name, COUNT(DISTINCT all_members.user_id) AS member_count FROM teams t JOIN team_members access_member ON access_member.team_id = t.id AND access_member.user_id = ? JOIN users owner ON owner.id = t.owner_id JOIN team_members all_members ON all_members.team_id = t.id GROUP BY t.id, t.name, t.owner_id, owner.name ORDER BY t.updated_at DESC`, [userId]); return rows; }

export async function listTournaments(userId) { const [rows] = await pool.query(`SELECT DISTINCT t.id, t.name, t.status, t.tournament_date, t.registration_end_at, r.status AS registration_status, tm.team_id, teams.name AS team_name, (SELECT CONCAT(rd.round_number, '|', rd.name) FROM rounds rd JOIN \`groups\` gg ON gg.round_id = rd.id JOIN group_teams gtt ON gtt.group_id = gg.id WHERE rd.tournament_id = t.id AND gtt.team_id = tm.team_id ORDER BY rd.round_number DESC LIMIT 1) AS current_round, (SELECT gg.name FROM rounds rd JOIN \`groups\` gg ON gg.round_id = rd.id JOIN group_teams gtt ON gtt.group_id = gg.id WHERE rd.tournament_id = t.id AND gtt.team_id = tm.team_id ORDER BY rd.round_number DESC LIMIT 1) AS current_group FROM tournaments t JOIN registrations r ON r.tournament_id = t.id JOIN teams ON teams.id = r.team_id JOIN team_members tm ON tm.team_id = r.team_id AND tm.user_id = ? WHERE r.status IN ('PENDING','VERIFIED') ORDER BY t.status = 'LIVE' DESC, t.tournament_date IS NULL, t.tournament_date ASC LIMIT 20`, [userId]); return rows; }

export async function listUpcomingMatches(userId) { const [rows] = await pool.query(`SELECT DISTINCT m.id, m.name, m.match_number, m.status, m.scheduled_at, t.id AS tournament_id, t.name AS tournament_name, rd.id AS round_id, rd.name AS round_name, gg.id AS group_id, gg.name AS group_name, teams.id AS team_id, teams.name AS team_name FROM matches m JOIN \`groups\` gg ON gg.id = m.group_id JOIN rounds rd ON rd.id = gg.round_id JOIN tournaments t ON t.id = rd.tournament_id JOIN group_teams gt ON gt.group_id = gg.id JOIN teams ON teams.id = gt.team_id JOIN team_members tm ON tm.team_id = teams.id AND tm.user_id = ? JOIN registrations r ON r.team_id = teams.id AND r.tournament_id = t.id AND r.status = 'VERIFIED' WHERE m.status <> 'COMPLETED' AND t.status = 'LIVE' AND m.scheduled_at IS NOT NULL ORDER BY m.scheduled_at ASC LIMIT 5`, [userId]); return rows; }

export async function listRecentResults(userId) { const [rows] = await pool.query(`SELECT mr.id, mr.points, mr.kills, mr.placement, mr.result_text, mr.created_at, m.id AS match_id, m.name AS match_name, t.id AS tournament_id, t.name AS tournament_name, rd.name AS round_name, gg.name AS group_name, teams.name AS team_name FROM match_results mr JOIN matches m ON m.id = mr.match_id JOIN \`groups\` gg ON gg.id = m.group_id JOIN rounds rd ON rd.id = gg.round_id JOIN tournaments t ON t.id = rd.tournament_id JOIN teams ON teams.id = mr.team_id JOIN team_members tm ON tm.team_id = teams.id AND tm.user_id = ? JOIN registrations r ON r.team_id = teams.id AND r.tournament_id = t.id AND r.status = 'VERIFIED' ORDER BY mr.created_at DESC LIMIT 6`, [userId]); return rows; }

export async function listLeaderboardSnapshots(userId) { const [rows] = await pool.query(`SELECT r.tournament_id, t.name AS tournament_name, rd.id AS round_id, rd.name AS round_name, gg.id AS group_id, gg.name AS group_name, le.team_id, teams.name AS team_name, SUM(le.points) AS points, SUM(le.kills) AS kills FROM leaderboard_entries le JOIN matches m ON m.id = le.match_id JOIN \`groups\` gg ON gg.id = m.group_id JOIN rounds rd ON rd.id = gg.round_id JOIN tournaments t ON t.id = rd.tournament_id JOIN teams ON teams.id = le.team_id JOIN team_members tm ON tm.team_id = teams.id AND tm.user_id = ? JOIN registrations r ON r.team_id = teams.id AND r.tournament_id = t.id AND r.status = 'VERIFIED' GROUP BY r.tournament_id, t.name, rd.id, rd.name, gg.id, gg.name, le.team_id, teams.name ORDER BY t.status = 'LIVE' DESC, points DESC LIMIT 10`, [userId]); return rows; }

export async function listAnnouncements(userId) { const [rows] = await pool.query(`SELECT DISTINCT a.id, a.tournament_id, t.name AS tournament_name, a.message, a.created_by, u.name AS creator_name, a.created_at FROM announcements a JOIN tournaments t ON t.id = a.tournament_id JOIN users u ON u.id = a.created_by JOIN registrations r ON r.tournament_id = t.id AND r.status IN ('PENDING','VERIFIED') JOIN team_members tm ON tm.team_id = r.team_id AND tm.user_id = ? ORDER BY a.created_at DESC, a.id DESC LIMIT 8`, [userId]); return rows; }
