import { errorResponses } from '../errors/AppError.js';
import * as repository from '../repositories/competitionRepository.js';
import { countRoundQualifications } from './resultsService.js';

const roundTransitions = { NOT_STARTED: ['IN_PROGRESS'], IN_PROGRESS: ['COMPLETED'] };
const groupTransitions = { NOT_STARTED: ['IN_PROGRESS'], IN_PROGRESS: ['COMPLETED'] };
const matchTransitions = { SCHEDULED: ['LIVE'], LIVE: ['COMPLETED'] };
const owner = (context, organizerId) => { if (!context || context.organizer_id !== organizerId) throw errorResponses.notFound('Competition resource not found'); };
const liveTournament = (context) => { if (context.tournament_status !== 'LIVE') throw errorResponses.conflict('Tournament must be LIVE for competition operations'); };
function transition(current, next, map, label) { if (next !== current && !map[current]?.includes(next)) throw errorResponses.conflict(`Invalid ${label} transition from ${current} to ${next}`); }
function mapError(error) { if (['TEAM_NOT_VERIFIED', 'TEAM_ALREADY_ASSIGNED', 'TEAM_NOT_QUALIFIED', 'GROUP_CAPACITY'].includes(error.code)) throw errorResponses.conflict(error.message); throw error; }
function serializeMatch(row) { return row && { id: row.id, groupId: row.group_id, matchNumber: row.match_number, name: row.name, status: row.status, scheduledAt: row.scheduled_at, startedAt: row.started_at, completedAt: row.completed_at, createdAt: row.created_at, updatedAt: row.updated_at }; }
function serializeGroup(row) { return row && { id: row.id, roundId: row.round_id, name: row.name, status: row.status, groupSize: row.group_size, roomId: row.room_id, roomPassword: row.room_password, startedAt: row.started_at, completedAt: row.completed_at, createdAt: row.created_at, updatedAt: row.updated_at, teams: (row.teams || []).map((team) => ({ id: team.id, name: team.name, assignedAt: team.assigned_at })), matches: (row.matches || []).map(serializeMatch) }; }
function serializeRound(row) { return row && { id: row.id, tournamentId: row.tournament_id, roundNumber: row.round_number, name: row.name, status: row.status, startedAt: row.started_at, completedAt: row.completed_at, createdAt: row.created_at, updatedAt: row.updated_at }; }

export async function listTournamentRounds(tournamentId, organizerId) { const tournament = await repository.getTournamentContext(tournamentId); owner(tournament, organizerId); return (await repository.listRounds(tournamentId)).map(serializeRound); }
export async function getRound(roundId, organizerId) { const context = await repository.getRoundContext(roundId); owner(context, organizerId); return serializeRound(await repository.findRound(roundId)); }
export async function createTournamentRound(tournamentId, input, organizerId) { const tournament = await repository.getTournamentContext(tournamentId); owner(tournament, organizerId); liveTournament({ tournament_status: tournament.status }); const rounds = await repository.listRounds(tournamentId); const previous = rounds.at(-1); const expectedNumber = (previous?.round_number || 0) + 1; if (Number(input.roundNumber) !== expectedNumber) throw errorResponses.conflict(`The next round must be numbered ${expectedNumber}`); if (previous && previous.status !== 'COMPLETED') throw errorResponses.conflict('The previous round must be completed before creating the next round'); return serializeRound(await repository.createRound(tournamentId, input)); }
export async function completeRound(roundId, organizerId) { const context = await repository.getRoundContext(roundId); owner(context, organizerId); transition(context.status, 'COMPLETED', roundTransitions, 'round'); if (await repository.countIncompleteGroups(roundId)) throw errorResponses.conflict('Every group must be completed before the round'); if (!(await countRoundQualifications(roundId))) throw errorResponses.conflict('At least one qualifying team must be selected before the round'); return serializeRound(await repository.updateRound(roundId, 'COMPLETED')); }
export async function updateRoundStatus(roundId, status, organizerId) { const context = await repository.getRoundContext(roundId); owner(context, organizerId); liveTournament(context); transition(context.status, status, roundTransitions, 'round'); return serializeRound(await repository.updateRound(roundId, status)); }

export async function listRoundGroups(roundId, organizerId) { const context = await repository.getRoundContext(roundId); owner(context, organizerId); return (await repository.listGroups(roundId)).map(serializeGroup); }
export async function listPlayerTournamentGroups(tournamentId, userId) { const context = await repository.getTournamentContext(tournamentId); if (!context || (context.organizer_id !== userId && !(await repository.isPlayerAssignedToTournament(tournamentId, userId)))) throw errorResponses.notFound('Tournament not found'); return (await repository.listPlayerTournamentGroups(tournamentId, userId)).map(serializeGroup); }
export async function listEligibleRoundTeams(roundId, organizerId) { const context = await repository.getRoundContext(roundId); owner(context, organizerId); return repository.listEligibleTeams(roundId); }
export async function getGroup(groupId, userId) { const context = await repository.getGroupContext(groupId); if (!context || (context.organizer_id !== userId && !(await repository.isPlayerAssignedToGroup(groupId, userId)))) throw errorResponses.notFound('Group not found'); return serializeGroup(await repository.findGroup(groupId)); }
export async function createRoundGroup(roundId, input, organizerId) { const context = await repository.getRoundContext(roundId); owner(context, organizerId); liveTournament(context); if (context.status === 'COMPLETED') throw errorResponses.conflict('Completed rounds are read-only'); return serializeGroup(await repository.createGroup(roundId, input)); }
export async function updateRoundGroup(groupId, input, organizerId) { const context = await repository.getGroupContext(groupId); owner(context, organizerId); liveTournament(context); if (context.status === 'COMPLETED' && input.status !== 'COMPLETED') throw errorResponses.conflict('Completed groups are read-only'); if (input.status) { transition(context.status, input.status, groupTransitions, 'group'); if (input.status === 'COMPLETED' && await repository.countIncompleteMatches(groupId)) throw errorResponses.conflict('Every match must be completed before the group'); } return serializeGroup(await repository.updateGroup(groupId, input)); }
export async function assignVerifiedTeam(groupId, teamId, organizerId) { const context = await repository.getGroupContext(groupId); owner(context, organizerId); liveTournament(context); if (context.status === 'COMPLETED') throw errorResponses.conflict('Completed groups are read-only'); try { return serializeGroup(await repository.assignTeam(groupId, teamId)); } catch (error) { return mapError(error); } }
export async function removeAssignedTeam(groupId, teamId, organizerId) { const context = await repository.getGroupContext(groupId); owner(context, organizerId); if (context.status === 'COMPLETED') throw errorResponses.conflict('Completed groups are read-only'); return serializeGroup(await repository.removeTeam(groupId, teamId)); }

export async function listGroupMatches(groupId, userId) { const context = await repository.getGroupContext(groupId); if (!context || (context.organizer_id !== userId && !(await repository.isPlayerAssignedToGroup(groupId, userId)))) throw errorResponses.notFound('Group not found'); return (await repository.listMatches(groupId)).map(serializeMatch); }
export async function getMatch(matchId, userId) { const context = await repository.getMatchContext(matchId); if (!context || (context.organizer_id !== userId && !(await repository.isPlayerAssignedToGroup(context.group_id, userId)))) throw errorResponses.notFound('Match not found'); return serializeMatch(await repository.findMatch(matchId)); }
export async function createGroupMatch(groupId, input, organizerId) { const context = await repository.getGroupContext(groupId); owner(context, organizerId); liveTournament(context); if (context.status === 'COMPLETED') throw errorResponses.conflict('Completed groups are read-only'); return serializeMatch(await repository.createMatch(groupId, input)); }
export async function updateGroupMatch(matchId, input, organizerId) { const context = await repository.getMatchContext(matchId); owner(context, organizerId); liveTournament(context); transition(context.status, input.status || context.status, matchTransitions, 'match'); if (context.status === 'COMPLETED' && input.status !== 'COMPLETED') throw errorResponses.conflict('Completed matches are read-only'); return serializeMatch(await repository.updateMatch(matchId, input)); }
export async function completeMatch(matchId, organizerId) { return updateGroupMatch(matchId, { status: 'COMPLETED' }, organizerId); }
