import { getCurrentIdentity } from './identityService.js';
import * as repository from '../repositories/playerDashboardRepository.js';

function mapSummary(row) { return { teams: Number(row.teams), activeTournaments: Number(row.active_tournaments), upcomingMatches: Number(row.upcoming_matches), completedTournaments: Number(row.completed_tournaments) }; }
function mapTournament(row) { return { id: row.id, name: row.name, status: row.status, tournamentDate: row.tournament_date, registrationEndAt: row.registration_end_at, registrationStatus: row.registration_status, teamId: row.team_id, teamName: row.team_name, currentRound: row.current_round ? row.current_round.split('|')[1] : null, currentGroup: row.current_group }; }
function mapMatch(row) { return { id: row.id, name: row.name, matchNumber: row.match_number, status: row.status, scheduledAt: row.scheduled_at, tournamentId: row.tournament_id, tournamentName: row.tournament_name, roundId: row.round_id, roundName: row.round_name, groupId: row.group_id, groupName: row.group_name, teamId: row.team_id, teamName: row.team_name }; }
function mapResult(row) { return { id: row.id, matchId: row.match_id, matchName: row.match_name, tournamentId: row.tournament_id, tournamentName: row.tournament_name, roundName: row.round_name, groupName: row.group_name, teamName: row.team_name, points: Number(row.points), kills: Number(row.kills), placement: row.placement, resultText: row.result_text, createdAt: row.created_at }; }
function mapLeaderboard(row) { return { tournamentId: row.tournament_id, tournamentName: row.tournament_name, roundId: row.round_id, roundName: row.round_name, groupId: row.group_id, groupName: row.group_name, teamId: row.team_id, teamName: row.team_name, points: Number(row.points), kills: Number(row.kills) }; }
function mapAnnouncement(row) { return { id: row.id, tournamentId: row.tournament_id, tournamentName: row.tournament_name, message: row.message, creatorName: row.creator_name, createdAt: row.created_at }; }

export async function getPlayerDashboard(userId) { const [user, summary, teams, tournaments, upcomingMatches, recentResults, leaderboardSnapshots, announcements, notifications] = await Promise.all([getCurrentIdentity(userId), repository.getSummary(userId), repository.listTeams(userId), repository.listTournaments(userId), repository.listUpcomingMatches(userId), repository.listRecentResults(userId), repository.listLeaderboardSnapshots(userId), repository.listAnnouncements(userId), import('../repositories/communicationRepository.js').then((module) => module.listNotifications(userId))]); return { user, summary: mapSummary(summary), teams, activeTournaments: tournaments.map(mapTournament), upcomingMatches: upcomingMatches.map(mapMatch), recentResults: recentResults.map(mapResult), leaderboardSnapshots: leaderboardSnapshots.map(mapLeaderboard), recentAnnouncements: announcements.map(mapAnnouncement), notifications: notifications.slice(0, 8).map((item) => ({ id: item.id, tournamentId: item.tournament_id, type: item.type, content: item.content, readAt: item.read_at, createdAt: item.created_at })), actionRequired: notifications.filter((item) => !item.read_at).slice(0, 5).map((item) => ({ id: item.id, tournamentId: item.tournament_id, type: item.type, content: item.content, createdAt: item.created_at })) }; }
